# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Blog Tutorial
site_description: an example blog set up following the tutorial
site_url: https://jerrylee.github.io

theme:
  name: material

plugins:
  - search
  - blog
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js